http:
  middleware:
    headers:
      response:
        Access-Control-Allow-Origin: ["$http.request.header.Origin"]
        Access-Control-Allow-Methods: ["GET,POST,OPTIONS,PUT,DELETE"]
        Access-Control-Allow-Headers: ["Authorization,Content-Type,X-Requested-With"]
        Access-Control-Allow-Credentials: ["true"]
